function getSocialMediaIssueHunterMenu() {
  return [
    '🎯 *TikTok Issue Hunter — Engine Blueprint*',
    '',
    '*Definisi*',
    '- Issue Hunter fokus menemukan isu naik (emerging issue), narasi dominan, dan pola amplifikasi akun di TikTok.',
    '- Prioritas: deteksi narasi yang mulai berkembang sebelum menjadi viral.',
    '',
    '*1) Arsitektur Sistem Issue Hunter TikTok*',
    'TikTok Data Source',
    '→ Data Collector (caption, hashtag, komentar, akun, waktu)',
    '→ Text Processing (cleaning, normalize, entity extraction)',
    '→ Embedding Model (text → vector)',
    '→ Clustering Engine (issue discovery)',
    '→ Issue Labeling (top keyword + entity)',
    '→ Network Mapping (akun, hashtag, audio, url)',
    '→ Trend Detection (burst detection)',
    '',
    '*2) Data minimal yang wajib dikumpulkan*',
    '- video_id, caption, hashtags, author_id, create_time, like_count, comment_count, share_count, audio_id, mention.',
    '- Tambahan penting: komentar, reply komentar, hashtag co-occurrence, audio reuse.',
    '',
    '*3) Feature extraction untuk issue detection*',
    '- TikTok dipengaruhi kombinasi hashtag + audio + caption.',
    '- Feature vector praktis:',
    '  feature_vector = embedding(caption) + hashtag_vector + entity_vector + audio_vector',
    '',
    '*4) Clustering paling efektif*',
    '- Gunakan Embedding + HDBSCAN (opsional UMAP sebelum clustering).',
    '- Keunggulan: tidak perlu set jumlah cluster dan tetap kuat menangkap isu kecil/emerging.',
    '- Output: cluster isu (A/B/C) + noise untuk konten random.',
    '',
    '*5) Label otomatis per isu*',
    '- Ambil top keywords, top hashtag, top entity per cluster.',
    '- Format label: "ISU: <entitas/aksi/lokasi>".',
    '- Contoh: "ISU: Demo Mahasiswa Surabaya".',
    '',
    '*6) Burst detection (isu naik)*',
    '- Rumus: burst_score = volume_now / average_volume_last_7_days.',
    '- Trigger early warning jika burst_score > 3.',
    '',
    '*7) Network mapping TikTok*',
    '- Graph: Account→Video, Video→Hashtag, Video→Audio, Account→Mention, Account→Comment.',
    '- Lanjutkan community detection (Louvain/Leiden) untuk menemukan cluster aktor pendorong isu/amplifikasi.',
    '',
    '*8) Deteksi akun amplifikasi / koordinasi*',
    '- Reuse audio yang sama dalam window waktu dekat.',
    '- Hashtag sama berulang lintas akun.',
    '- Waktu posting berdekatan.',
    '- Similarity caption tinggi (embedding similarity).',
    '',
    '*9) Output dashboard issue hunter*',
    '- Top issues harian: label isu, volume video, akun unik, burst score.',
    '- Tambahan: peta komunitas akun, video sumber isu, timeline perkembangan isu.',
    '',
    '*10) Skema data operasional (acuan implementasi CICERO)*',
    '- tiktok_video(video_id, author_id, caption, create_time, audio_id, like_count, comment_count).',
    '- tiktok_hashtag(video_id, hashtag).',
    '- tiktok_issue_cluster(cluster_id, label, volume, burst_score).',
    '- tiktok_issue_map(video_id, cluster_id).',
    '',
    '*11) Toolset umum*',
    '- Playwright/Puppeteer (collection), sentence-transformers (embedding), HDBSCAN (clustering), NetworkX (graph), Neo4j (visual relasi).',
    '',
    '*12) Upgrade high-impact*',
    '- Narrative Detection.',
    '- Actor Influence Score.',
    '- Early Warning System (pre-viral detection).',
    '',
    'Catatan integrasi: menu ini adalah blueprint operasional TikTok Issue Hunter untuk orkestrasi dan implementasi lanjutan di engine CICERO.'
  ].join('\n');
}

module.exports = { getSocialMediaIssueHunterMenu };
